import { AddName, AddSelect } from "@/utils/QuickConfig"
export default {
	theme: {
		...AddName("主题"),
		...AddSelect("primary"),
		value: ["primary", "default", "success", "warning", "danger"],
	},
	size: {
		name: "尺寸",
		...AddSelect("md"),
		value: ["md", "sm", "lg"],
	},
	type: {
		name: "类型",
		value: [
			"add",
			"add-round",
			"add-round-fill",
			"minus",
			"minus-round",
			"minus-round-fill",
			"arrow-top",
			"arrow-bottom",
			"arrow-left",
			"arrow-right",
			"info-round",
			"info-round-fill",
			"warning-round",
			"warning-round-fill",
			"right",
			"right-round",
			"right-round-fill",
			"wrong",
			"wrong-round",
			"wrong-round-fill",
			"question-round",
			"question-round-fill",
			"required",
			"broadcast",
			"deletekey",
			"keyboard",
			"search",
			"date",
			"time",
		],
		...AddSelect("add"),
	},
	position: {
		h: 2,
		w: 2,
	},
}
